### PR TITLE
Run the testsuite on multiple compiler versions

### LINKED ISSUE #222: Add all currently supported clang versions in the CI
See [this github action](https://github.com/jvoisin/fortify-headers/blob/master/.github/workflows/testsuite.yaml) for example.

### PR DESCRIPTION
**Pull request by jvoisin**
This should fix #222

### CODE REVIEW

**Comment by thestinger** [comment]
@jvoisin Clang 14 and GCC 12 are the oldest versions I want to support.

**Comment by jvoisin** [comment]
Is it a problem to keep them in the CI if they're working?

**Comment by thestinger** [comment]
I don't want to have to support older compiler versions than the ones in Debian stable. It will stop people using modern language / compiler features for hardened_malloc.

**Comment by jvoisin** [comment]
Fair enough

**Comment by thestinger** [comment]
It says there's an error in syntax and isn't running the jobs.

**Comment by jvoisin** [comment]
Grmbl, yaml is hard.

**Pull request merged**
