### PR TITLE
delete pyc files in test folder

### PR DESCRIPTION
**Pull request by adrelanos**

### CODE REVIEW

**Comment by thestinger** [comment]
Can you try changing __init__.py to /usr/bin/env python3 and then try this again? My `python` is `python3` so it's using `python3` here. I'd rather have this use `python3` everywhere and then only clean the files generated by `python3`.

**Comment by adrelanos** [comment]
That doesn't work.

**Comment by adrelanos** [comment]
Though, setting a  [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) everywhere might be good nevertheless.

**Comment by thestinger** [comment]
Don't know what you mean by doesn't work.

**Comment by thestinger** [comment]
I pushed a change switching `python` to `python3` in the Makefile.

**Comment by thestinger** [comment]
Can you reopen this for the Python3 cache?

**Comment by adrelanos** [comment]
Daniel Micay:
> Don't know what you mean by doesn't work.
> 


By it doesn't work, I meant to say the pyc files are still being created
and not covered by make clean.

**Comment by thestinger** [comment]
With https://github.com/GrapheneOS/hardened_malloc/commit/b9ebf47c7cfd6ca0ba29c25181789dd383a73f1b it should now be using Python3 so it will create the Python3 cache directory instead of these files. That could be removed by `clean` instead.

**Comment by adrelanos** [comment]
Great! Thank you for working on hardened_malloc!

Btw we've been considering enabling hardened_malloc by default in Whonix, and Kicksecure.

https://forums.whonix.org/t/hardened-malloc-hardened-memory-allocator/7474/69

**Pull request closed without merging**
