### PR TITLE
Don't ignore the return value of the testsuite

### PR DESCRIPTION
**Pull request by jvoisin**
This should make the CI red when something is broken, partially fixing 171

### CODE REVIEW

**Comment by thestinger** [comment]
Clang issue probably needs to be fixed first. I'm not sure why it wouldn't be working.

**Comment by jvoisin** [comment]
Me neither, otherwise I would have send a PR to fix the issue :/

**Comment by thestinger** [comment]
I ended up figuring it out. Clang doesn't enable sized deallocation by default. We don't enable this feature in GrapheneOS at the moment due to incredibly low security value so we never noticed.

**Comment by jvoisin** [comment]
Nice to see that the CI is useful \o/

**Pull request merged**
