### PR TITLE
Add the CONFIG_ENFORCE_INIT configuration option

### PR DESCRIPTION
**Pull request by cyanlemons**

### CODE REVIEW

**Comment by thestinger** [comment]
This really shouldn't be optional. It's always incorrect if this is violated. Even if the early initialization is disabled, this doesn't get tripped without there being a serious bug in the application.

**Comment by thestinger** [comment]
Try disabling the early initialization:

```
// trigger early initialization to set up pthread_atfork and protect state as soon as possible
COLD __attribute__((constructor(101))) static void trigger_early_init(void) {
    // avoid calling init directly to skip it if this isn't the malloc implementation
    h_free(h_malloc(16));
}
```

You'll notice it still works in anything that's not buggy, because code paths like `malloc` initialize the allocator. It's just going to abort if something calls `free` with a non-NULL pointer before it's initialized anyway, because it's an invalid pointer.

**Comment by thestinger** [comment]
You'll just get an abort when it tries to look up the allocation in the region allocation table. There is no table yet so you'll likely get a crash from a NULL pointer deference. The `enforce_init` calls simply produce an error instead of an uglier way of finding the error that's harder to debug. It should still be safe without `enforce_init`, but I don't see how it'd ever help you to disable it and `enforce_init` is not a performance issue since it's only needed in the large allocation code paths.

**Comment by cyanlemons** [comment]
I must have just gotten lucky the first time around when testing this. When using a build of this branch, I went back to the same page and couldn't get the Firefox tab to crash, so I assumed it worked. But after reading your comments and trying again, this time for a bit longer, it did indeed segfault in the end.

I suppose as a temporary hack on my end, I could simply add something like this to the relevant functions.
```c
if (!is_init()) {
    return;
}
```

I was initially going to try and rebuild Firefox with jemalloc disabled, but then I realized how long it actually takes to build Firefox.

**Pull request closed without merging**
